### PR TITLE
Fix the error that occurred when HF_HUB_OFFLINE = 1

### PR DESCRIPTION
**Pull request by fallingmeteorite**
"huggingface_hub" disable online mode for all HTTP requests, but some operations still make HTTP requests, so I've added a modification to this section
This will not affect usage in online mode or report errors in offline mode
When you are online, you cannot access the Internet

### CODE REVIEW

**Comment by fallingmeteorite** [comment]
I usually use it on-prem + offline, I would prefer it not checking HF repeatedly, while still being able to work locally.
So I'm submitting this merge, hoping that someone like me who needs it can run normally and not trigger an error

**Comment by narugo1992** [comment]
hmmmm, bro

do you know this code will simply kill all the network connections?

actually not all the users are using imgutils 100% offline.

the better solution is to use all these code in your personal script, not in the imgutils (even the `imgutils/__init__.py`) 😨 

i wont merge this before this got changed to an optional one.

**Comment by fallingmeteorite** [comment]
emmmm, I know he'll reject all network requests.

but I haven't figured out how to make it optional yet.

maybe I'll need to change it to see if I can gracefully make it optional.

**Comment by fallingmeteorite** [comment]
my code level is not very high, please forgive me

**Pull request closed without merging**
